### ISSUE TITLE
When running this action as part of a strategy: matrix: only one comment is added to PR

### ISSUE THREAD

**Issue by mattpu-sportsbet** [badsyntax/github-action-issue-comment#7]
If the workflow needs to run this action across multiple accounts / stacks, this action only seems to result in the last comment being present on the PR. If using strategy max-parallel: 1 I do not encounter any issues, so seems related to asyncronicity of comments being added. Each flow in the matrix outputs a unique message ID but only one results on the PR.

As a side issue, I frequently see this error crop up when calling actions/github-script@v5:
`(node:1609) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by badsyntax** [comment]
Thanks for the bug report. I've fixed the warnings with PR https://github.com/badsyntax/github-action-issue-comment/pull/8

About the parallel runs, are you able to share a condensed version of your actions workflow file?

**Comment by mattpu-sportsbet** [comment]
Here's the condensed version of a job i'm using to roll over multiple accounts each with their own identically named stack, I'm using to diff-check them all when a PR comes into the templates. Without `max-parallel: 1` I wasn't getting more than one comment, and obviously it slows the job down quite a bit. I also have multiple environments and templates on top of the below 'dev' job and so once you multiply that out you can see I would have many comments simultaneously getting written.

I was hitting some rate limiting which meant keeping this is not useless, but would be interesting to see if you can re-produce.


    strategy:
      max-parallel: 1
      matrix:
        account: [aa-a, aa-b, aa-c, aa-d, aa-e, aa-f]

    runs-on: ubuntu-20.04

    env:
      region: ap-southeast-2
      accountname: ${{ matrix.account }}-dev

    steps:
      - uses: actions/checkout@v2

      - id: accountid
        run: |
          echo "[get account id command]" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.accountid }}:role/ActionRole
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: ${{ env.region }}

      - name: Check CloudFormation Stack
        continue-on-error: true
        uses: badsyntax/github-action-aws-cloudformation@master
        id: get-diff
        if:
        with:
          stack-name: deploy-role
          template: cf/roles/deploy-role-${{ env.accountname }}.yaml
          apply-change-set: false
          aws-region: ${{ env.region }}

      - name: Comment on Pull Request
        continue-on-error: true
        uses: badsyntax/github-action-issue-comment@master
        if: github.event_name == 'pull_request'
        with:
          action: 'create-clean'
          template: '.github/templates/pr-comment-template.hbs'
          id: cloudformation
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          template-inputs: |
            {
              "changes": ${{ steps.get-diff.outputs.changes }},
              "outputs": ${{ steps.get-diff.outputs.outputs }},
              "accountname": "${{ env.accountname }}",
              "accountid": "${{ env.accountid }}",
              "applyChangeSet": false
            }

Also modified the template to include the account name and id
`| AccountId | AccountName |
| :--------- | :----------- |
|{{inputs.accountid}} | {{inputs.accountname}} |`

**Comment by badsyntax** [comment]
@mattpu-sportsbet thanks for the example yaml! and apologies for the delay for looking into this.

I've done some testing with https://github.com/badsyntax/github-action-issue-comment/pull/10 and i better understand what's going on now.

Each comment has to have an id that's unique for the PR. When you enable matrix runs, the `id: cloudformation` id is shared between runs and this causes all types of problems. 

To fix you should append the matrix id to the comment id, for example:

```
id: cloudformation-${{ matrix.account }}
```

Let me know if that fixes it for you?

**Comment by mattpu-sportsbet** [comment]
@badsyntax Ok yeah that seems to work well - I can remove the parallel: 1 setting and all the job dependencies, and now seem to be able to run this across multiple jobs & matrices. Possible it just needs slightly clearer documentation around that id uniqueness, I didn't spot anything on that when reading earlier.

I'm also not seeing the timeout from earlier so looks like that is fixed too, thanks!

**Comment by badsyntax** [comment]
Awesome, thanks for verifying. Indeed this information was not explicit in the README. I've since added a note about this: https://github.com/badsyntax/github-action-issue-comment#comment-id
